//
// Created by Oem on 14.03.2024.
//

#ifndef COSMICVOYAGER_DEFINITION_H
#define COSMICVOYAGER_DEFINITION_H

#define CONTINUE 0
#define AP_CALL_SPACE_PIRATES 1
#define SP_RUN_AWAY 1
#define SP_FIGHT 2
#define SP_BARGAIN 3
#define SP_RUN_AWAY_FAILED 4
#define SP_RUN_AWAY_INADEQUATE_FUEL 5
#define SP_BARGAIN_CALL_FIGHT 6
#define ASTEROID_BELT 0
#define ABANDONED_PLANET 1
#define SPACE_PIRATES 2


#endif //COSMICVOYAGER_DEFINITION_H
