//
// Created by Oem on 14.03.2024.
//

#ifndef COSMICVOYAGER_DEFINITION_H
#define COSMICVOYAGER_DEFINITION_H

#define AP_CALL_SPACE_PIRATES 1
#define SP_RUN 1
#define SP_FIGHT 2
#define SP_BARGAIN 3
#define SP_RUN_AWAY_SUCCESS 4
#define SP_RUN_AWAY_FAILURE 5
#define SP_RUN_AWAY_NOT_ENOUGH_FUEL 6
#define SP_BARGAIN_CALL_FIGHT 7
#define CONTINUE 0

#endif //COSMICVOYAGER_DEFINITION_H
